web/router.ex
defmodule AdamczDotCom.Router do
  use AdamczDotCom.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug AdamczDotCom.Auth, repo: AdamczDotCom.Repo
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", AdamczDotCom do
    pipe_through :browser # Use the default browser stack
    resources "/users", UserController, only: [:index, :show, :new, :create, :edit, :update, :delete]
    resources "/blog", BlogController, only: [:index, :show, :new, 
        :create, :edit, :update], param: "slug"
    resources "/sessions", SessionController, only: [:new, :create, :delete]
    resources "/tags", TagController, only: [:index, :show, :new, :create, :edit, :update, :delete]
    get "/about", PageController, :about
    get "/dev", PageController, :dev
    get "/music", PageController, :music
    get "/resume", PageController, :resume
    get "/", PageController, :index
  end

  # Other scopes may use custom stacks.
  # scope "/api", AdamczDotCom do
  #   pipe_through :api
  # end
end

web/views/layout_view.ex
defmodule AdamczDotCom.LayoutView do
  use AdamczDotCom.Web, :view
end

web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="website of web developer and composer Adam Czerepinski">
    <meta name="author" content="Adam Czerepinski">
    <title>Adam Czerepinski</title>
    <link href="https://fonts.googleapis.com/css?family=Open+Sans|Source+Code+Pro|Oswald" rel="stylesheet">
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
  </head>

  <body>

    <nav role="navigation" class="navbar">
      <div class="navbar__logo">
        <a class="navbar__link" href="/">CZ</a>
      </div>
      <div class="navbar__links">
        <ul>
          <li><%= link "RESUME", class: "navbar__link", to: page_path(@conn, :resume) %></li>
          <li><%= link "MUSIC", class: "navbar__link", to: page_path(@conn, :music) %></li>
          <li><%= link "BLOG", class: "navbar__link", to: blog_path(@conn, :index) %></li>
          <%= if @current_user do %>
          <li><%= link "LOGOUT", class: "navbar__link", to: session_path(@conn, :delete, @current_user), method: "delete" %></li>
          <% end %>
        </ul>
      </div>
    </nav>

      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>

      <main role="main" class="main">
        <%= render @view_module, @view_template, assigns %>
      </main>

    </div> <!-- /container -->
    <footer class="footer">
      <div class="footer__icons">
        <a class="footer__link--home" href="/">CZ</a>
      <!-- entypo icons by Daniel Bruce www.entypo.com -->

        <a href="https://github.com/aczerepinski" target="_blank">
          <div class="svg-icon">
            <svg version="1.1" id="Github" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
            viewBox="0 0 20 20" enable-background="new 0 0 20 20" xml:space="preserve">
            <path d="M13.18,11.309c-0.718,0-1.3,0.807-1.3,1.799c0,0.994,0.582,1.801,1.3,1.801s1.3-0.807,1.3-1.801
            C14.479,12.116,13.898,11.309,13.18,11.309z M17.706,6.626c0.149-0.365,0.155-2.439-0.635-4.426c0,0-1.811,0.199-4.551,2.08
            c-0.575-0.16-1.548-0.238-2.519-0.238c-0.973,0-1.945,0.078-2.52,0.238C4.74,2.399,2.929,2.2,2.929,2.2
            C2.14,4.187,2.148,6.261,2.295,6.626C1.367,7.634,0.8,8.845,0.8,10.497c0,7.186,5.963,7.301,7.467,7.301
            c0.342,0,1.018,0.002,1.734,0.002c0.715,0,1.392-0.002,1.732-0.002c1.506,0,7.467-0.115,7.467-7.301
            C19.2,8.845,18.634,7.634,17.706,6.626z M10.028,16.915H9.972c-3.771,0-6.709-0.449-6.709-4.115c0-0.879,0.31-1.693,1.047-2.369
            c1.227-1.127,3.305-0.531,5.662-0.531c0.01,0,0.02,0,0.029,0c0.01,0,0.018,0,0.027,0c2.357,0,4.436-0.596,5.664,0.531
            c0.735,0.676,1.045,1.49,1.045,2.369C16.737,16.466,13.8,16.915,10.028,16.915z M6.821,11.309c-0.718,0-1.3,0.807-1.3,1.799
            c0,0.994,0.582,1.801,1.3,1.801c0.719,0,1.301-0.807,1.301-1.801C8.122,12.116,7.54,11.309,6.821,11.309z"/>
            </svg>
          </div>
        </a>

        <a href="https://www.linkedin.com/in/adamcz" target="_blank">
          <div class="svg-icon">
            <svg version="1.1" id="LinkedIn" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
            viewBox="0 0 20 20" enable-background="new 0 0 20 20" xml:space="preserve">
            <path d="M5,3c0,1.1-0.7,2-2,2C1.8,5,1,4.1,1,3.1C1,2,1.8,1,3,1S5,1.9,5,3z M1,19h4V6H1V19z M14.6,6.2c-2.1,0-3.3,1.2-3.8,2h-0.1
            l-0.2-1.7H6.9C6.9,7.6,7,8.9,7,10.4V19h4v-7.1c0-0.4,0-0.7,0.1-1c0.3-0.7,0.8-1.6,1.9-1.6c1.4,0,2,1.2,2,2.8V19h4v-7.4
            C19,7.9,17.1,6.2,14.6,6.2z"/>
            </svg>
          </div>
        </a>

        <a href="https://twitter.com/adamczerepinski" target="_blank">
          <div class="svg-icon">
            <svg version="1.1" id="Twitter" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
            viewBox="0 0 20 20" enable-background="new 0 0 20 20" xml:space="preserve">
            <path d="M17.316,6.246c0.008,0.162,0.011,0.326,0.011,0.488c0,4.99-3.797,10.742-10.74,10.742c-2.133,0-4.116-0.625-5.787-1.697
            c0.296,0.035,0.596,0.053,0.9,0.053c1.77,0,3.397-0.604,4.688-1.615c-1.651-0.031-3.046-1.121-3.526-2.621
            c0.23,0.043,0.467,0.066,0.71,0.066c0.345,0,0.679-0.045,0.995-0.131c-1.727-0.348-3.028-1.873-3.028-3.703c0-0.016,0-0.031,0-0.047
            c0.509,0.283,1.092,0.453,1.71,0.473c-1.013-0.678-1.68-1.832-1.68-3.143c0-0.691,0.186-1.34,0.512-1.898
            C3.942,5.498,6.725,7,9.862,7.158C9.798,6.881,9.765,6.594,9.765,6.297c0-2.084,1.689-3.773,3.774-3.773
            c1.086,0,2.067,0.457,2.756,1.191c0.859-0.17,1.667-0.484,2.397-0.916c-0.282,0.881-0.881,1.621-1.66,2.088
            c0.764-0.092,1.49-0.293,2.168-0.594C18.694,5.051,18.054,5.715,17.316,6.246z"/>
            </svg>
          </div>
        </a>
      </div>
    </footer>
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>